
# SPDX-License-Identifier: GPL-2.0

dtb-$(CONFIG_ARCH_MXC) += sp2-imx8mp.dtb
dtbo-$(CONFIG_ARCH_MXC) += 10inch-overlay.dtbo
dtbo-$(CONFIG_ARCH_MXC) += 7inch-overlay.dtbo
dtbo-$(CONFIG_ARCH_MXC) += 7dsi-overlay.dtbo
dtbo-$(CONFIG_ARCH_MXC) += awcm276masur-overlay.dtbo
dtbo-$(CONFIG_ARCH_MXC) += awcm276mapur-overlay.dtbo
dtbo-$(CONFIG_ARCH_MXC) += eth0-overlay.dtbo
dtbo-$(CONFIG_ARCH_MXC) += cma400mb-overlay.dtbo
dtbo-$(CONFIG_ARCH_MXC) += cma750mb-overlay.dtbo
dtbo-$(CONFIG_ARCH_MXC) += cma950mb-overlay.dtbo
dtbo-$(CONFIG_ARCH_MXC) += 10inch-overlay.dtbo
dtbo-$(CONFIG_ARCH_MXC) += 7inch-overlay.dtbo
dtbo-$(CONFIG_ARCH_MXC) += 7dsi-overlay.dtbo
dtbo-$(CONFIG_ARCH_MXC) += 7rlcd-overlay.dtbo
dtbo-$(CONFIG_ARCH_MXC) += awcm276masur-overlay.dtbo
dtbo-$(CONFIG_ARCH_MXC) += awcm276mapur-overlay.dtbo
dtbo-$(CONFIG_ARCH_MXC) += eth0-overlay.dtbo
dtbo-$(CONFIG_ARCH_MXC) += cma400mb-overlay.dtbo
dtbo-$(CONFIG_ARCH_MXC) += cma750mb-overlay.dtbo
dtbo-$(CONFIG_ARCH_MXC) += cma950mb-overlay.dtbo
dtbo-$(CONFIG_ARCH_MXC) += 23inch-overlay.dtbo
dtbo-$(CONFIG_ARCH_MXC) += ts-ili2132-overlay.dtbo

# enable creation of __symbols__ node
DTC_FLAGS += -@

always-y        := $(dtbo-y)
